# Generated by Django 3.0.5 on 2020-06-04 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200604_1039'),
        ('maps', '0002_auto_20200417_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='aoi',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='core.AOI'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='job',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Job'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='core.Project'),
        ),
    ]
