# Generated by Django 3.0.5 on 2020-06-04 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200604_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='ontology_reference',
            field=models.URLField(default=''),
        ),
    ]
